export const countryList = [
	"Afghanistan",
	"Albania",
	"Algeria",
	"American Samoa",
	"Andorra",
	"Angola",
	"Anguilla",
	"Antarctica",
	"Antigua and Barbuda",
	"Argentina",
	"Armenia",
	"Aruba",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Bahamas (the)",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belarus",
	"Belgium",
	"Belize",
	"Benin",
	"Bermuda",
	"Bhutan",
	"Bolivia (Plurinational State of)",
	"Bonaire, Sint Eustatius and Saba",
	"Bosnia and Herzegovina",
	"Botswana",
	"Bouvet Island",
	"Brazil",
	"British Indian Ocean Territory (the)",
	"Brunei Darussalam",
	"Bulgaria",
	"Burkina Faso",
	"Burundi",
	"Cabo Verde",
	"Cambodia",
	"Cameroon",
	"Canada",
	"Cayman Islands (the)",
	"Central African Republic (the)",
	"Chad",
	"Chile",
	"China",
	"Christmas Island",
	"Cocos (Keeling) Islands (the)",
	"Colombia",
	"Comoros (the)",
	"Congo (the Democratic Republic of the)",
	"Congo (the)",
	"Cook Islands (the)",
	"Costa Rica",
	"Croatia",
	"Cuba",
	"Curaçao",
	"Cyprus",
	"Czechia",
	"Côte d'Ivoire",
	"Denmark",
	"Djibouti",
	"Dominica",
	"Dominican Republic (the)",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"Equatorial Guinea",
	"Eritrea",
	"Estonia",
	"Eswatini",
	"Ethiopia",
	"Falkland Islands (the) [Malvinas]",
	"Faroe Islands (the)",
	"Fiji",
	"Finland",
	"France",
	"French Guiana",
	"French Polynesia",
	"French Southern Territories (the)",
	"Gabon",
	"Gambia (the)",
	"Georgia",
	"Germany",
	"Ghana",
	"Gibraltar",
	"Greece",
	"Greenland",
	"Grenada",
	"Guadeloupe",
	"Guam",
	"Guatemala",
	"Guernsey",
	"Guinea",
	"Guinea-Bissau",
	"Guyana",
	"Haiti",
	"Heard Island and McDonald Islands",
	"Holy See (the)",
	"Honduras",
	"Hong Kong",
	"Hungary",
	"Iceland",
	"India",
	"Indonesia",
	"Iran (Islamic Republic of)",
	"Iraq",
	"Ireland",
	"Isle of Man",
	"Israel",
	"Italy",
	"Jamaica",
	"Japan",
	"Jersey",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kiribati",
	"Korea (the Democratic People's Republic of)",
	"Korea (the Republic of)",
	"Kuwait",
	"Kyrgyzstan",
	"Lao People's Democratic Republic (the)",
	"Latvia",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Macao",
	"Madagascar",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mali",
	"Malta",
	"Marshall Islands (the)",
	"Martinique",
	"Mauritania",
	"Mauritius",
	"Mayotte",
	"Mexico",
	"Micronesia (Federated States of)",
	"Moldova (the Republic of)",
	"Monaco",
	"Mongolia",
	"Montenegro",
	"Montserrat",
	"Morocco",
	"Mozambique",
	"Myanmar",
	"Namibia",
	"Nauru",
	"Nepal",
	"Netherlands (the)",
	"New Caledonia",
	"New Zealand",
	"Nicaragua",
	"Niger (the)",
	"Nigeria",
	"Niue",
	"Norfolk Island",
	"Northern Mariana Islands (the)",
	"Norway",
	"Oman",
	"Pakistan",
	"Palau",
	"Palestine, State of",
	"Panama",
	"Papua New Guinea",
	"Paraguay",
	"Peru",
	"Philippines (the)",
	"Pitcairn",
	"Poland",
	"Portugal",
	"Puerto Rico",
	"Qatar",
	"Republic of North Macedonia",
	"Romania",
	"Russian Federation (the)",
	"Rwanda",
	"Réunion",
	"Saint Barthélemy",
	"Saint Helena, Ascension and Tristan da Cunha",
	"Saint Kitts and Nevis",
	"Saint Lucia",
	"Saint Martin (French part)",
	"Saint Pierre and Miquelon",
	"Saint Vincent and the Grenadines",
	"Samoa",
	"San Marino",
	"Sao Tome and Principe",
	"Saudi Arabia",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierra Leone",
	"Singapore",
	"Sint Maarten (Dutch part)",
	"Slovakia",
	"Slovenia",
	"Solomon Islands",
	"Somalia",
	"South Africa",
	"South Georgia and the South Sandwich Islands",
	"South Sudan",
	"Spain",
	"Sri Lanka",
	"Sudan (the)",
	"Suriname",
	"Svalbard and Jan Mayen",
	"Sweden",
	"Switzerland",
	"Syrian Arab Republic",
	"Taiwan (Province of China)",
	"Tajikistan",
	"Tanzania, United Republic of",
	"Thailand",
	"Timor-Leste",
	"Togo",
	"Tokelau",
	"Tonga",
	"Trinidad and Tobago",
	"Tunisia",
	"Turkey",
	"Turkmenistan",
	"Turks and Caicos Islands (the)",
	"Tuvalu",
	"Uganda",
	"Ukraine",
	"United Arab Emirates (the)",
	"United Kingdom of Great Britain and Northern Ireland (the)",
	"United States Minor Outlying Islands (the)",
	"United States of America (the)",
	"Uruguay",
	"Uzbekistan",
	"Vanuatu",
	"Venezuela (Bolivarian Republic of)",
	"Viet Nam",
	"Virgin Islands (British)",
	"Virgin Islands (U.S.)",
	"Wallis and Futuna",
	"Western Sahara",
	"Yemen",
	"Zambia",
	"Zimbabwe",
	"Åland Islands"
]

export const dummieData = [
  {
		id: 1,
		name: "Daggy",
    price: "$1000 USD",
		avgRating: 9,
		quantity: 7,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit culpa velit rerum iure consequatur porro, sed quas dolor nobis atque ipsum. Inventore, repellendus! Accusamus atque explicabo iste nostrum? Natus, ad!",
    images:
      ["https://www.funcage.com/blog/wp-content/uploads/2013/11/Weird-Products-That-Actually-Exist-021.jpg"],
    created: "7 days ago",
  },
  {
		id: 2,
		name: "Anubra",
		avgRating: 10,
		quantity: 8,
    price: "$1000 USD",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit culpa velit rerum iure consequatur porro, sed quas dolor nobis atque ipsum. Inventore, repellendus! Accusamus atque explicabo iste nostrum? Natus, ad!",
    images:
      ["https://i1.wp.com/www.sopitas.com/wp-content/uploads/2017/01/comercial-random-japon.jpg"],
    created: "23 hours ago",
  },
  {
		id: 3,
		name: "Josef",
		avgRating: 5,
		quantity: 2,
    price: "$1000 USD",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit culpa velit rerum iure consequatur porro, sed quas dolor nobis atque ipsum. Inventore, repellendus! Accusamus atque explicabo iste nostrum? Natus, ad!",
    images: [
      "https://www.redcandy.co.uk/blog/wp-content/uploads/2015/08/blog-pic-nessie.jpg",
    ],
    created: "A few seconds ago",
  },
  {
		id: 4,
		name: "Sage",
    price: "$1000 USD",
		avgRating: 8.5,
		quantity: 7,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit culpa velit rerum iure consequatur porro, sed quas dolor nobis atque ipsum. Inventore, repellendus! Accusamus atque explicabo iste nostrum? Natus, ad!",
    images: [
      "https://teslasonly.com/wp-content/uploads/2019/05/1558699022.jpg",
    ],
    created: "A few hours ago",
  },
	{
		id: 5,
		name: "Acer Nitro 5",
		price: "$1000 USD",
		avgRating: 7,
		quantity: 4,
		description:
			'Acer Nitro 5 AN517-41-R0RZ Gaming Laptop viene con estas especificaciones de alto nivel: AMD Ryzen 7 5800H Octa-Core Processor 3.2GHz con precisión Boost hasta 4.4GHz, pantalla panorámica Full HD de 17.3" con retroiluminación LED IPS (resolución 1920 x 1080; relación de aspecto 16:9; 144 Hz. Fresh Rate, NVIDIA GeForce RTX 3060 GPU para portátil con 6 GB de GDDR6 VRAM, NVIDIA DLSS, NVIDIA Redimensionable BAR, NVIDIA Dynamic Boost 2.0, NVIDIA GPU Boost, 16GB DDR4 3200MHz de memoria, 1TB PCIe NVMe SSD (2 x PCIe M.2 x PCIe M.2 PCIe M.2 x Ranuras | 1 Ranura disponible), 1 - Bahía de disco duro disponible, DTS: X Ultra Audio, Acer True Harmony Technology, dos altavoces estéreo integrados, Acer Purified.Tecnología de voz con dos micrófonos integrados, Intel Wireless Wi-Fi 6 AX200 802.11ax Dual-Band 2.4GHz y 5GHz con tecnología MU-MIMO 2x2 (Velocidad máxima de hasta 2.4Gbps), Killer Ethernet E2600000 Gbps), Killer E2 Gbps. 0 10/LAN Ethernet Gigabit 100/1000, Bluetooth 5.1, cámara web HD (1280 x 720) compatible con rango dinámico súper alto (SHDR), 1 puerto USB 3.2 tipo C Gen 2 (hasta 10 Gbps), 1 puerto USB 3.2 Gen 2 (con carga de apagado), 2 puertos USB 3.2, 1 - HDMI Puerto 2.1 con soporte HDCP, teclado retroiluminado RGB de 4 zonas, Windows 10 Home, batería de iones de litio, hasta 9 horas de duración de la batería, 6 libras. | 6 libras (sólo unidad del sistema) (NH.QARAA.001)',
		images: [
			"https://m.media-amazon.com/images/I/81Z8NvO2TFL._AC_SL1500_.jpg",
			"https://images.idgesg.net/images/article/2020/11/acer-nitro-5-an515-44-r99q-vents-100865209-large.jpg?auto=webp&quality=85,70",
			"https://m.media-amazon.com/images/I/81PUD0rM2NL._AC_SL1500_.jpg",
			"https://res.cloudinary.com/walmart-labs/image/upload/w_960,dpr_auto,f_auto,q_auto:best/mg/gm/1p/images/product-images/img_large/00019319977512l.jpg",
			"https://static.acer.com/up/Resource/Acer/Laptops/Nitro_5/rev-jan-2021-intel/20210329/Acer-Nitro5-KSP1-640.jpg",
		],
    created: "Some time ago",
	},
];